services:
  - type: web
    name: video-library
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn src.app:create_app()
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FLASK_ENV
        value: production
      - key: JWT_COOKIE_SECURE 
        value: true
